---
- name: Extract the zipped artifact
  become: true
  unarchive:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/

- name: Start the app
  shell: |
    echo "ls output: "
    ls
    npm install
    pm2 stop default
    pm2 start npm -- start